#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : extras
Version  : 0.0.3
Release  : 13
URL      : https://pypi.python.org/packages/source/e/extras/extras-0.0.3.tar.gz
Source0  : https://pypi.python.org/packages/source/e/extras/extras-0.0.3.tar.gz
Summary  : Useful extra bits for Python - things that shold be in the standard library
Group    : Development/Tools
License  : MIT
Requires: extras-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : testtools
BuildRequires : testtools-python
Patch1: 0001-Add-trove-classifiers-specifying-Python-3-support.patch

%description
======
extras
======
extras is a set of extensions to the Python standard library, originally
written to make the code within testtools cleaner, but now split out for
general use outside of a testing context.

%package python
Summary: python components for the extras package.
Group: Default

%description python
python components for the extras package.


%prep
%setup -q -n extras-0.0.3
%patch1 -p1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd py2 ; py.test-2.7 ; popd
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
